# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f0f95783e7e83196033adcb1d71cd52e"
name = "ReviewForge"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_products,write_products,read_metaobjects,write_metaobjects"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "/api/proxy/reviews"
prefix = "apps"
subpath = "reviews"
