# shopify.app.toml

client_id = "f0f95783e7e83196033adcb1d71cd52e"
name = "ReviewForge"
application_url = "https://review-app-seven-gamma.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_products,write_products,read_metaobjects,write_metaobjects"

[auth]
redirect_urls = ["https://review-app-seven-gamma.vercel.app/auth/callback"]

[app_proxy]
# IMPORTANT: This must be the *base* proxy URL, not the full /reviews path.
url = "https://review-app-seven-gamma.vercel.app/api/proxy"
prefix = "apps"
subpath = "reviews"
